settings:
gradients:
  white:
    colours: [0x444f, 0xffff]
materials:
  plastic: !Diffuse
    gradient_id: white
  mirror: !Reflective
    gradient_id: white
    reflectivity: 0.9
  glass: !Refractive
    gradient_id: white
    refractive_index: 1.5
meshes:
  cube: ./assets/meshes/cube.obj
  icosphere: ./assets/meshes/icosphere.obj
instances:
  left_cube:
    mesh_id: cube
    material_id: plastic
    translation: [-1.0, 0.0, 0.0]
  right_cube:
    mesh_id: cube
    material_id: plastic
    translation: [1.0, 0.0, 0.0]
    rotation: [10.0, 15.0, 20.0]
    scale: 0.5
cameras:
  - resolution: [270, 480]
    num_tiles: [4, 4]
    super_sampling: 3
  