print_tiles_to_terminal: false
scene:
  meshes:
    # cube: ./assets/meshes/cube.obj
    icosphere: ./assets/meshes/icosphere.obj
  objects:
    obj0:
      mesh_id: icosphere
lighting:
  sun_position: [-40.0, 70.0, 100.0]
cameras:
  camera 0:
    position: [-2.0, 2.0, 2.0]
    target: [0.0, 0.0, 0.0]
    field_of_view: 90.0
    super_samples_per_axis: 1
    image_resolution: [5, 5]
    tile_resolution: [400, 400]
  # camera 1:
  #   position: [10.0, 0.0, 0.0]
  #   target: [0.0, 0.0, 0.0]
  #   field_of_view: 90.0
  #   image_resolution: [10, 10]
  #   tile_resolution: [108, 192]
