settings:
  output_directory: output
  smoothing_length: 1.0e-2
  min_weight: 0.01
  max_loops: 1000
  mesh_bvh_max_children: 2
  mesh_bvh_max_depth: 100
  scene_bvh_max_children: 2
  scene_bvh_max_depth: 100
spectra:
  green: [0x000000ff, 0x00dd33ff]
  blue: [0x000000ff, 0x0000ffff]
  yellow: [0xffffffff, 0xffff00ff]
  gray: [0x444444ff, 0xddddddff]
meshes:
  cube: ./assets/meshes/shapes/simple/cube.obj
  icosphere: ./assets/meshes/shapes/simple/icosphere.obj
  square: ./assets/meshes/shapes/simple/square.obj
materials:
  grass: !Diffuse
    spectrum_id: green
  sky: !Diffuse
    spectrum_id: blue
entities:
  - material_id: grass
    mesh_id: square
    scale: 0.2
  - material_id: grass
    mesh_id: icosphere
    scale: 0.2
    translation: [0, 0.5, 0]
  - material_id: grass
    mesh_id: icosphere
    scale: 0.2
    translation: [0, 0.5, 100]
lights:
  - position: [10, 30, 200]
    intensity: 1.0
    colour: 0xffffaaff
cameras:
  main_camera:
    engine: !Outlined 2.0
    position: [-10, 8, 6]
    look_at: [0, 0, 0]
    field_of_view: 15
    resolution: [8000, 6000]
    num_tiles: [8, 12]
    super_samples_per_axis: 2
