//! # `Photo`
//!
//! `Photo` is a utility library for manipulating images in Rust.

#![deny(absolute_paths_not_starting_with_crate)]
#![deny(ambiguous_negative_literals)]
#![deny(clippy::all)]
#![deny(clippy::cargo)]
#![deny(clippy::complexity)]
#![deny(clippy::correctness)]
#![deny(clippy::nursery)]
#![deny(clippy::pedantic)]
#![deny(clippy::perf)]
#![deny(clippy::restriction)]
#![deny(clippy::style)]
#![deny(clippy::suspicious)]
#![deny(closure_returning_async_block)]
#![deny(dead_code)]
#![deny(deprecated_safe_2024)]
#![deny(deref_into_dyn_supertrait)]
#![deny(edition_2024_expr_fragment_specifier)]
// #![deny(elided_lifetimes_in_paths)]
#![deny(explicit_outlives_requirements)]
#![deny(ffi_unwind_calls)]
#![deny(future_incompatible)]
// #![deny(fuzzy_provenance_casts)]
#![deny(if_let_rescope)]
#![deny(impl_trait_overcaptures)]
#![deny(impl_trait_redundant_captures)]
#![deny(improper_ctypes)]
#![deny(keyword_idents_2018)]
#![deny(keyword_idents_2024)]
#![deny(keyword_idents)]
#![deny(let_underscore_drop)]
// #![deny(lossy_provenance_casts)]
#![deny(macro_use_extern_crate)]
#![deny(meta_variable_misuse)]
#![deny(missing_copy_implementations)]
#![deny(missing_debug_implementations)]
#![deny(missing_docs)]
#![deny(missing_unsafe_on_extern)]
// #![deny(multiple_supertrait_upcastable)]
// #![deny(must_not_suspend)]
#![deny(non_ascii_idents)]
// #![deny(non_exhaustive_omitted_patterns)]
#![deny(nonstandard_style)]
#![deny(path_statements)]
#![deny(redundant_imports)]
#![deny(redundant_lifetimes)]
// #![deny(rust_2018_idioms)]
// #![deny(rust_2021_incompatible_closure_captures)]
// #![deny(rust_2021_incompatible_or_patterns)]
// #![deny(rust_2021_prefixes_incompatible_syntax)]
// #![deny(rust_2021_prelude_collisions)]
// #![deny(rust_2024_guarded_string_incompatible_syntax)]
// #![deny(rust_2024_incompatible_pat)]
// #![deny(rust_2024_prelude_collisions)]
#![deny(rustdoc::broken_intra_doc_links)]
#![deny(single_use_lifetimes)]
// #![deny(supertrait_item_shadowing_definition)]
// #![deny(supertrait_item_shadowing_usage)]
#![deny(tail_expr_drop_order)]
#![deny(trivial_casts)]
#![deny(trivial_numeric_casts)]
#![deny(unit_bindings)]
#![deny(unnameable_types)]
// #![deny(unqualified_local_imports)]
#![deny(unreachable_code)]
#![deny(unreachable_pub)]
#![deny(unsafe_attr_outside_unsafe)]
#![deny(unsafe_code)]
#![deny(unsafe_op_in_unsafe_fn)]
#![deny(unstable_features)]
#![deny(unused_assignments)]
#![deny(unused_crate_dependencies)]
#![deny(unused_extern_crates)]
#![deny(unused_import_braces)]
#![deny(unused_imports)]
#![deny(unused_lifetimes)]
#![deny(unused_macro_rules)]
#![deny(unused_must_use)]
#![deny(unused_mut)]
#![deny(unused_qualifications)]
#![deny(unused_results)]
#![deny(unused_variables)]
#![deny(unused)]
#![deny(variant_size_differences)]
#![deny(warnings)]
#![allow(clippy::arbitrary_source_item_ordering, reason = "Unhelpful")]
#![allow(clippy::arithmetic_side_effects, reason = "Too restrictive for this crate.")]
#![allow(clippy::blanket_clippy_restriction_lints, reason = "More lints are always better.")]
#![allow(clippy::implicit_return, reason = "Implicit returns are idiomatic in Rust.")]
#![allow(clippy::indexing_slicing, reason = "Too restrictive for this crate.")]
#![allow(
    clippy::integer_division_remainder_used,
    reason = "This crate should not be considered suitable for cryptographic use."
)]
#![allow(clippy::integer_division, reason = "Too restrictive for this crate.")]
#![allow(
    clippy::pub_use,
    reason = "It is intended to expose the `Direction` and `Transform` types at the crate level."
)]

mod channels;
mod image;

pub use channels::Channels;
pub use image::Image;
